# Generated by Django 4.2.20 on 2025-04-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionplan'),
        ),
    ]
