# Generated by Django 4.2.20 on 2025-03-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='ai_relevance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.RemoveField(
            model_name='content',
            name='tags',
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(related_name='contents', to='content.tag'),
        ),
    ]
